modLoader = "javafml"
loaderVersion = "[36,)"
license = "BSD-3-Clause"

[[mods]]
modId = "slide_show"
version = "${version}"
displayName = "Slideshow"
credits = "ustc_zzzz, BloCamLimb, Jonathan Ho"
authors = "3TUSK"
description = "A simple slideshow projector in Minecraft."
logoFile = "icon.png"

[[dependencies.slide_show]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slide_show]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slide_show]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"