modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "slide_show"
version = "${version}"
displayName = "Slide Show"
authors = "3TUSK, ustc_zzzz, BloCamLimb, Zbx1425"
description = "Simple slide show projector in Minecraft."

[[dependencies.slide_show]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slide_show]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"